- name: System Update
  yum:
    name: "*"
    state: latest

- name: Install required soft
  yum:
    name: [policycoreutils-python]
    state: latest

- name: add gitlab repository
  shell:
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash

- name: Install GitLab package
  yum:
    name: gitlab-ce
    state: latest

- name: Reconfigure GitLab (first run).
  shell: gitlab-ctl reconfigure
