- include: "{{ansible_os_family}}.yml"

# set soft link
- block: 
  - name: Create link for gitlab
    file:
      src: '{{item.src}}'
      dest: '{{item.dest}}'
      state: link
    with_items:
      - {src: /opt/gitlab/,dest: /data/wwwroot/gitlab}
      - {src: /etc/gitlab/gitlab.rb,dest: /data/config/gitlab}

  # display version and service state of components
  - name: Get GitLab version
    shell: sudo sh -c "cat /opt/gitlab/version-manifest.txt | grep gitlab-{{gitlab_distribution}} 1>> /data/logs/install_version.txt"

  - name: Check GitLab Service
    shell: gitlab-ctl status  | grep gitlab-workhorse
    register: check_gitlab_service
    notify: check_gitlab_service
    
  - name: Move change_gitlab_password to  /tmp/
    template:
        src: change_gitlab_password.py
        dest: /tmp/change_gitlab_password.py
