# install gitlab
- debug:
    msg: Gitlab - {{ gitlab_distribution }} will be installed

- include: "{{ansible_os_family}}.yml"

# configure gitlab

# set soft link
- name: set soft link
  shell: |
    ln -sb /opt/gitlab  /data/wwwroot/gitlab
    ln -sb /etc/gitlab/gitlab.rb /data/config/gitlab

# display version and service state of components
- name: Get GitLab version
  shell: cat /opt/gitlab/version-manifest.txt | grep gitlab-ce
  register: check_gitlab_version
  notify: check_gitlab_version

- name: Check GitLab Service
  shell: gitlab-ctl status  | grep gitlab-workhorse
  register: check_gitlab_service
  notify: check_gitlab_service
