# install gitlab
- debug:
    msg: Gitlab - {{ gitlab_distribution }} will be installed

- include: "{{ansible_os_family}}.yml"

# configure gitlab

# set soft link
- name: set soft link
  shell: |
    ln -sf /opt/gitlab  /data/wwwroot
    ln -sf /etc/gitlab/gitlab.rb /data/config

# display version and service state of components
- name: Get GitLab version
  shell: sudo sh -c "cat /opt/gitlab/version-manifest.txt | grep gitlab-ce 1>> /data/logs/install_version.txt"

- name: Check GitLab Service
  shell: gitlab-ctl status  | grep gitlab-workhorse
  register: check_gitlab_service
  notify: check_gitlab_service
