- name: Install required soft
  yum:
    name: [curl, policycoreutils-python, openssh-server, perl]
    state: latest

- name: Add the GitLab package repository and install the required packages
  shell:
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-{{gitlab_distribution}}/script.rpm.sh | sudo bash

- name: Install GitLab package
  yum:
    name: gitlab-{{gitlab_distribution}}
    state: latest

- name: Reconfigure GitLab (first run).
  shell: gitlab-ctl reconfigure