# 核心任务
- name: gitlab
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True
  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'gitlab_distribution_number'
      prompt: "Please choose the number for Gitlab distribution \n
      1: Gitlab CE(default)\n
      2: Gitlab EE\n"
      private: no
      default: 1

  vars:
    temp_ver:
      '1': 'ce'
      '2': 'ee'
    gitlab_distribution: "{{temp_ver[gitlab_distribution_number]}}" 
    
  pre_tasks:  
    - debug:
        msg: Gitlab - {{ gitlab_distribution }} will be installed
           
  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud"}     
    - { role: gitlab, tags: "gitlab"}
    - { role: role_docker, tags: "role_docker" }
    - { role: role_preend, tags: "role_preend" }
    - { role: role_end, tags: "role_end"}