# # 服务器前置任务(ubuntu使用)
- name: pre_gitlab
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python
     ignore_errors: True


# # 核心任务

- name: gitlab
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True
  vars_prompt:
    - name: 'gitlab_distribution_number'
      prompt: "Please choose the number for Gitlab distribution \n
      1: Gitlab CE(default)\n
      2: Gitlab EE\n"
      private: no
      default: 1

  vars:
    temp_ver:
      '1': 'ce'
      '2': 'ee'
    gitlab_distribution: "{{temp_ver[gitlab_distribution_number]}}" 
    
  pre_tasks:  
    - debug:
        msg: Gitlab - {{ gitlab_distribution }} will be installed
           
  roles:
    - { role: common, tags: "common"}  
    - { role: cloud, tags: "cloud"}     
    - { role: gitlab, tags: "gitlab"}
    - { role: end, tags: "end"}
