# # 服务器前置任务(ubuntu使用)
- name: gitlab
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt-get -y install python


# # 核心任务

- name: gitlab
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  roles:
    - { role: common, tags: "common"}      
    - { role: gitlab, tags: "gitlab"}
    - { role: end, tags: "end"}




    


                                                                                                    