- name: gitlab
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True
  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'gitlab_distribution_selection'
      prompt: "Please choose the number for Gitlab distribution \n
      1: Gitlab CE(default)\n
      2: Gitlab EE\n"
      private: no
      default: 1

    - name: 'gitlab_portainer_selection'
      prompt: "Do you want to install Portainer of Docker? \n
      1: Yes, Install it\n
      2: No, Don't install it\n"
      private: no
      default: 1

      
  vars:
    gitlab_distribution_select:
      '1': 'ce'
      '2': 'ee'
    gitlab_portainer_select:
      '1': True
      'y': True
      'Y': True
      '2': False
      'n': False
      'N': False
    
    gitlab_distribution: "{{gitlab_distribution_select[gitlab_distribution_selection]}}" 
    gitlab_portainer: "{{gitlab_portainer_select[gitlab_portainer_selection]}}" 
    
  pre_tasks:  
    - debug:
        msg: Gitlab - {{ gitlab_distribution }} will be installed and gitlab_portainer={{gitlab_portainer}}

    - set_fact:
        docker_applications: []
      when: not gitlab_portainer 

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud"}
    - { role: role_docker, tags: "role_docker" }
    - { role: role_init, tags: "role_init"}
    - { role: gitlab, tags: "gitlab"}
    - { role: role_preend, tags: "role_preend" }
    - { role: role_end, tags: "role_end"}
